version: "3.8"

services:
    # PHP service
    apiv1:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/public/
        ports:
            - 9000:9000

    # Database Service
    databases:
        image: mysql:8.0
        container_name: mysql-database
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/

    nginx-server:
        image: nginx:latest
        volumes:
            - ./nginx/default.conf:/etc/nginx/default.conf
        ports:
            - "80:80"
        depends_on:
            - apiv1

volumes:
    db-data: ~
